"""Changed type of column balance to decimal instead of float

Revision ID: 17be43582882
Revises: 99804a976e5a
Create Date: 2025-03-31 23:04:52.308241

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17be43582882"
down_revision = "99804a976e5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
