"""Initial migration

Revision ID: 99804a976e5a
Revises: 
Create Date: 2025-03-23 20:46:10.536607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99804a976e5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
